// Chinese and English maps of provinces and cities
const provinceCityMapping = {
    '安徽省': 'Anhui',
    '北京市': 'Beijing',
    '福建省': 'Fujian',
    '甘肃省': 'Gansu',
    '广东省': 'Guangdong',
    '广西壮族自治区': 'Guangxi Zhuang Autonomous Region',
    '贵州省': 'Guizhou',
    '海南省': 'Hainan',
    '河北省': 'Hebei',
    '河南省': 'Henan',
    '黑龙江省': 'Heilongjiang',
    '湖北省': 'Hubei',
    '湖南省': 'Hunan',
    '吉林省': 'Jilin',
    '江苏省': 'Jiangsu',
    '江西省': 'Jiangxi',
    '辽宁省': 'Liaoning',
    '内蒙古自治区': 'Nei Monggol Autonomous Region',
    '宁夏回族自治区': 'Ningxia Hui Autonomous Region',
    '青海省': 'Qinghai',
    '山东省': 'Shandong',
    '山西省': 'Shanxi',
    '陕西省': 'Shaanxi',
    '上海市': 'Shanghai',
    '四川省': 'Sichuan',
    '天津市': 'Tianjin',
    '西藏自治区': 'Tibet Autonomous Region',
    '新疆维吾尔自治区': 'Xinjiang Uygur Autonomous Region',
    '云南省': 'Yunnan',
    '浙江省': 'Zhejiang',
    '重庆市': 'Chongqing',
    '香港省': 'HongKong',
    '澳门省': 'Macao',
    '台湾省': 'Taiwan',
    '南海诸岛': 'South China Sea Islands',
    "北京城区": "Beijing",
    "天津城区": "Tianjin",
    "上海城区": "Shanghai",
    "香港特别行政区": "Hong Kong Special Administrative Region",
    "澳门特别行政区": "Macau Special Administrative Region",
    "石家庄市": "Shijiazhuang",
    "唐山市": "Tangshan",
    "秦皇岛市": "Qinhuangdao",
    "邯郸市": "Handan",
    "邢台市": "Xingtai",
    "保定市": "Baoding",
    "张家口市": "Zhangjiakou",
    "承德市": "Chengde",
    "沧州市": "Cangzhou",
    "廊坊市": "Langfang",
    "衡水市": "Hengshui",
    "辛集市": "Xinji",
    "晋州市": "Jinzhou",
    "新乐市": "Xinle",
    "遵化市": "Zunhua",
    "迁安市": "Qian'an",
    "武安市": "Wu'an",
    "南宫市": "nangong",
    "沙河市": "shahe ",
    "涿州市": "Zhuozhou",
    "定州市": "Dingzhou",
    "安国市": "Anguo",
    "高碑店市": "Gaobeidian",
    "平泉市": "Pingquan",
    "泊头市": "Botou",
    "任丘市": "Renqiu",
    "黄骅市": "Huanghua",
    "河间市": "Hejian",
    "霸州市": "Bazhou",
    "三河市": "Sanhe",
    "深州市": "Shenzhou",
    "太原市": "Taiyuan",
    "大同市": "Datong",
    "阳泉市": "Yangquan",
    "长治市": "Changzhi",
    "晋城市": "Jincheng",
    "朔州市": "Shuozhou",
    "晋中市": "Jinzhong",
    "运城市": "Yuncheng",
    "忻州市": "xinzhou",
    "临汾市": "Linfen",
    "吕梁市": "Lvliang",
    "古交市": "Gujiao",
    "高平市": "gaoping",
    "介休市": "Jiexiu",
    "永济市": "Yongji",
    "河津市": "Hejin",
    "原平市": "Yuanping ",
    "侯马市": "Houma",
    "霍州市": "Huozhou",
    "孝义市": "Xiaoyi",
    "汾阳市": "Fenyang",
    "怀仁市": "Huairen",
    "呼和浩特市": "Hohhot",
    "包头市": "Baotou",
    "乌海市": "Wuhai",
    "赤峰市": "Chifeng",
    "通辽市": "Tongliao",
    "鄂尔多斯市": "ordos ",
    "呼伦贝尔市": "Hulunbuir",
    "巴彦淖尔市": "Bayannur",
    "乌兰察布市": "Ulanqab",
    "霍林郭勒市": "Huolingol Shi ",
    "满洲里市": "Manzhouli",
    "牙克石市": "Yakeshi",
    "扎兰屯市": "Zhalantun",
    "额尔古纳市": "Ergun ",
    "根河市": "Genhe",
    "丰镇市": "Fengzhen ",
    "乌兰浩特市": "Ulanhot",
    "阿尔山市": "Alshan",
    "二连浩特市": "Erenhot",
    "锡林浩特市": "Xilinhot",
    "沈阳市": "Shenyang",
    "大连市": "Dalian",
    "鞍山市": "Anshan",
    "抚顺市": "Fushun",
    "本溪市": "Benxi",
    "丹东市": "Dandong",
    "锦州市": "Jinzhou",
    "营口市": "Yingkou",
    "阜新市": "Fuxin",
    "辽阳市": "Liaoyang",
    "盘锦市": "Panjin",
    "铁岭市": "Tieling",
    "朝阳市": "Chaoyang",
    "葫芦岛市": "Huludao",
    "新民市": "Xinmin",
    "瓦房店市": "Wafangdian",
    "庄河市": "Zhuanghe",
    "海城市": "haicheng",
    "东港市": "donggang",
    "凤城市": "Fengcheng",
    "凌海市": "Linghai",
    "北镇市": "Beizhen",
    "盖州市": "Gaizhou",
    "大石桥市": "Dashiqiao",
    "灯塔市": "Dengta",
    "调兵山市": "Diaobingshan",
    "开原市": "Kaiyuan",
    "北票市": "Beipiao",
    "凌源市": "Lingyuan",
    "兴城市": "Xingcheng",
    "长春市": "Changchun",
    "吉林市": "Jilin",
    "四平市": "Siping",
    "辽源市": "Liaoyuan",
    "通化市": "Tonghua",
    "白山市": "Baishan",
    "松原市": "Songyuan",
    "白城市": "Baicheng",
    "榆树市": "Yushu",
    "德惠市": "Dehui",
    "蛟河市": "Jiaohe",
    "桦甸市": "Huadian",
    "舒兰市": "Shulan",
    "磐石市": "Panshi",
    "公主岭市": "Gongzhuling",
    "双辽市": "Shuangliao",
    "梅河口市": "Meihekou",
    "集安市": "Ji'an",
    "洮南市": "Taonan",
    "大安市": "Da'an",
    "临江市": "Linjiang ",
    "延吉市": "Yanji",
    "图们市": "Tumen",
    "敦化市": "dunhua",
    "珲春市": "HunChun",
    "龙井市": "Longjing",
    "和龙市": "Helong",
    "扶余市": "Fuyu",
    "哈尔滨市": "Harbin",
    "齐齐哈尔市": "Qiqihar",
    "黑河市": "Heihe",
    "大庆市": "Daqing",
    "伊春市": "Yichun",
    "鹤岗市": "Hegang",
    "佳木斯市": "Jiamusi",
    "双鸭山市": "Shuangyashan",
    "七台河市": "Qitaihe",
    "鸡西市": "Jixi",
    "牡丹江市": "Mudanjiang",
    "绥化市": "Suihua",
    "尚志市": "Shangzhi ",
    "五常市": "Wuchang",
    "讷河市": "Nehe",
    "北安市": "Beian ",
    "五大连池市": "Wudalianchi",
    "嫩江市": "Nenjiang",
    "铁力市": "Tieli ",
    "同江市": "Tongjiang",
    "富锦市": "Fujin",
    "虎林市": "Hulin",
    "密山市": "Mishan ",
    "绥芬河市": "Suifenhe",
    "海林市": "Hailin",
    "宁安市": "Ning'an",
    "安达市": "Anda",
    "肇东市": "Zhaodong",
    "海伦市": "Hailun ",
    "穆棱市": "Muling ",
    "东宁市": "Dongning",
    "抚远市": "Fuyuan",
    "漠河市": "Mohe",
    "南京市": "Nanjing",
    "徐州市": "Xuzhou",
    "连云港市": "Lianyungang ",
    "宿迁市": "Suqian",
    "淮安市": "Huai'an",
    "盐城市": "yancheng ",
    "扬州市": "Yangzhou",
    "泰州市": "Taizhou",
    "南通市": "Nantong",
    "镇江市": "Zhenjiang",
    "常州市": "Changzhou",
    "无锡市": "Wuxi",
    "苏州市": "Suzhou",
    "常熟市": "Changshu",
    "张家港市": "Zhangjiagang",
    "太仓市": "Taicang",
    "昆山市": "city of Kunshan",
    "江阴市": "Jiangyin",
    "宜兴市": "Yixing",
    "溧阳市": "Liyang",
    "扬中市": "yangzhong ",
    "句容市": "jurong ",
    "丹阳市": "Danyang",
    "如皋市": "Rugao ",
    "启东市": "qidong ",
    "海安市": "Hai'an",
    "高邮市": "Gaoyou",
    "仪征市": "Yizheng",
    "兴化市": "xinghua ",
    "泰兴市": "taixing ",
    "靖江市": "Jingjiang",
    "东台市": "Dongtai",
    "邳州市": "Pizhou ",
    "新沂市": "Xinyi",
    "杭州市": "Hangzhou",
    "宁波市": "Ningbo",
    "湖州市": "Huzhou",
    "嘉兴市": "Jiaxing",
    "舟山市": "Zhoushan",
    "绍兴市": "Shaoxing",
    "衢州市": "Quzhou",
    "金华市": "Jinhua",
    "台州市": "Taizhou",
    "温州市": "Wenzhou",
    "丽水市": "Lishui",
    "建德市": "Jiande ",
    "慈溪市": "Cixi",
    "余姚市": "Yuyao",
    "平湖市": "Pinghu ",
    "海宁市": "Haining",
    "桐乡市": "tongxiang ",
    "诸暨市": "Zhuji",
    "嵊州市": "Shengzhou",
    "江山市": "Jiangshan",
    "兰溪市": "Lanxi",
    "永康市": "Yongkang",
    "义乌市": "yiwu ",
    "东阳市": "Dongyang",
    "临海市": "Linhai",
    "温岭市": "Wenling",
    "瑞安市": "Rui'an",
    "乐清市": "Yueqing ",
    "龙港市": "Longgang",
    "龙泉市": "Longquan ",
    "玉环市": "Yuhuan",
    "合肥市": "Hefei",
    "芜湖市": "Wuhu",
    "蚌埠市": "Bengbu",
    "淮南市": "Huainan",
    "马鞍山市": "Ma'anshan",
    "淮北市": "Huaibei",
    "铜陵市": "tongling ",
    "安庆市": "Anqing",
    "黄山市": "Mount Huangshan",
    "滁州市": "Chuzhou",
    "阜阳市": "Fuyang",
    "宿州市": "Suzhou",
    "六安市": "Lu'an",
    "亳州市": "Bozhou",
    "池州市": "chizhou ",
    "宣城市": "Xuancheng",
    "巢湖市": "Chaohu",
    "桐城市": "Tongcheng ",
    "天长市": "tianchang ",
    "明光市": "Mingguang",
    "界首市": "Jieshou ",
    "宁国市": "Ningguo",
    "广德市": "Guangde",
    "潜山市": "Qianshan",
    "无为市": "Wuwei",
    "厦门市": "Xiamen",
    "福州市": "Fuzhou",
    "南平市": "Nanping",
    "三明市": "Sanming",
    "莆田市": "Putian",
    "泉州市": "Quanzhou",
    "漳州市": "Zhangzhou",
    "龙岩市": "Longyan",
    "宁德市": "Ningde",
    "福清市": "Fuqing",
    "邵武市": "Shaowu",
    "武夷山市": "Mount Wuyi",
    "建瓯市": "Jian'ou",
    "永安市": "Yong'an",
    "石狮市": "Shishi",
    "晋江市": "Jinjiang ",
    "南安市": "Nan'an",
    "龙海市": "Longhai ",
    "漳平市": "Zhangping",
    "福安市": "Fu'an",
    "福鼎市": "fuding ",
    "南昌市": "Nanchang",
    "九江市": "Jiujiang",
    "景德镇市": "Jingdezhen",
    "鹰潭市": "Yingtan",
    "新余市": "Xinyu",
    "萍乡市": "Pingxiang",
    "赣州市": "Ganzhou",
    "上饶市": "Shangrao",
    "抚州市": "Fuzhou",
    "宜春市": "Yichun",
    "吉安市": "Ji'an",
    "瑞昌市": "Ruichang",
    "共青城市": "Communist Youth",
    "庐山市": "Lushan",
    "乐平市": "Leping ",
    "瑞金市": "Ruijin",
    "德兴市": "Dexing ",
    "丰城市": "Fengcheng ",
    "樟树市": "zhangshu ",
    "高安市": "Gao'an",
    "井冈山市": "Jinggangshan ",
    "贵溪市": "Guixi ",
    "济南市": "Jinan",
    "青岛市": "Qingdao",
    "聊城市": "LiaoCheng ",
    "德州市": "Dezhou",
    "东营市": "Dongying",
    "淄博市": "Zibo",
    "潍坊市": "Weifang",
    "烟台市": "Yantai",
    "威海市": "Weihai",
    "日照市": "Rizhao",
    "临沂市": "Linyi",
    "枣庄市": "Zaozhuang",
    "济宁市": "Jining",
    "泰安市": "Tai'an",
    "滨州市": "Binzhou",
    "菏泽市": "HeZe ",
    "胶州市": "Jiaozhou",
    "平度市": "Pingdu",
    "莱西市": "Laixi",
    "临清市": "Linqing",
    "乐陵市": "Leling",
    "禹城市": "Yucheng",
    "安丘市": "Anqiu ",
    "昌邑市": "Changyi",
    "高密市": "Gaomi",
    "青州市": "Qingzhou",
    "诸城市": "Zhucheng",
    "寿光市": "Shouguang",
    "栖霞市": "Qixia",
    "海阳市": "Haiyang ",
    "龙口市": "Longkou",
    "莱阳市": "Laiyang",
    "莱州市": "Laizhou",
    "蓬莱市": "Penglai",
    "招远市": "Zhaoyuan",
    "荣成市": "Rongcheng",
    "乳山市": "Rushan",
    "滕州市": "Tengzhou",
    "曲阜市": "Qufu",
    "邹城市": "Zoucheng ",
    "新泰市": "Xintai",
    "肥城市": "Feicheng",
    "邹平市": "Zouping",
    "郑州市": "Zhengzhou",
    "开封市": "Kaifeng",
    "洛阳市": "Luoyang",
    "平顶山市": "Pingdingshan",
    "安阳市": "Anyang",
    "鹤壁市": "Hebi",
    "新乡市": "Xinxiang",
    "焦作市": "Jiaozuo",
    "濮阳市": "Puyang",
    "许昌市": "Xuchang",
    "漯河市": "Luohe",
    "三门峡市": "Sanmenxia",
    "南阳市": "Nanyang",
    "商丘市": "Shangqiu",
    "周口市": "Zhoukou ",
    "驻马店市": "Zhumadian",
    "信阳市": "Xinyang",
    "荥阳市": "xingyang ",
    "新郑市": "Xinzheng",
    "登封市": "Dengfeng ",
    "新密市": "Xinmi ",
    "偃师市": "Yanshi ",
    "孟州市": "Mengzhou ",
    "沁阳市": "Qinyang",
    "卫辉市": "Weihui",
    "辉县市": "huixian ",
    "长垣市": "Nagasaki",
    "林州市": "Linzhou",
    "禹州市": "Yuzhou",
    "长葛市": "Changge",
    "舞钢市": "Wugang",
    "义马市": "Yima",
    "灵宝市": "Lingbao",
    "项城市": "Xiangcheng",
    "巩义市": "Gongyi ",
    "邓州市": "Dengzhou ",
    "永城市": "Yongcheng ",
    "汝州市": "Ruzhou ",
    "济源市": "Jiyuan",
    "武汉市": "Wuhan",
    "十堰市": "Shiyan",
    "襄阳市": "Xiangyang ",
    "荆门市": "Jingmen",
    "孝感市": "Xiaogan",
    "黄冈市": "Huanggang",
    "鄂州市": "Ezhou",
    "黄石市": "Huangshi",
    "咸宁市": "Xianning ",
    "荆州市": "jingzhou ",
    "宜昌市": "Yichang",
    "随州市": "suizhou ",
    "丹江口市": "Danjiangkou",
    "老河口市": "Laohekou",
    "枣阳市": "Zaoyang",
    "宜城市": "Yicheng",
    "钟祥市": "Zhongxiang ",
    "京山市": "Jingshan",
    "汉川市": "Hanchuan",
    "应城市": "Yingcheng",
    "安陆市": "Anlu",
    "广水市": "Guangshui",
    "麻城市": "Macheng ",
    "武穴市": "Wuxue ",
    "大冶市": "Daye ",
    "赤壁市": "Chibi",
    "石首市": "Shishou",
    "洪湖市": "Honghu",
    "松滋市": "Songzi",
    "宜都市": "Yidu",
    "枝江市": "Zhijiang ",
    "当阳市": "Dangyang",
    "恩施市": "Enshi",
    "利川市": "Lichuan",
    "仙桃市": "Xiantao",
    "天门市": "Tianmen",
    "潜江市": "Qianjiang ",
    "长沙市": "Changsha",
    "衡阳市": "Hengyang",
    "张家界市": "Zhangjiajie",
    "常德市": "Changde",
    "益阳市": "Yiyang",
    "岳阳市": "Yueyang",
    "株洲市": "Zhuzhou",
    "湘潭市": "Xiangtan",
    "郴州市": "Chenzhou",
    "永州市": "Yongzhou",
    "邵阳市": "Shaoyang",
    "怀化市": "huaihua ",
    "娄底市": "Loudi",
    "耒阳市": "Leiyang",
    "常宁市": "Changning",
    "浏阳市": "Liuyang",
    "津市市": "Jinshi",
    "沅江市": "Yuanjiang",
    "汨罗市": "Miluo",
    "临湘市": "Linxiang",
    "醴陵市": "Liling",
    "湘乡市": "Xiangxiang ",
    "韶山市": "Shaoshan",
    "资兴市": "Zixing",
    "武冈市": "Wugang",
    "邵东市": "Shaodong",
    "洪江市": "Hongjiang",
    "冷水江市": "Lengshuijiang",
    "涟源市": "Lianyuan",
    "吉首市": "Jishou",
    "宁乡市": "Ningxiang",
    "广州市": "Guangzhou",
    "深圳市": "Shenzhen",
    "清远市": "Qingyuan",
    "韶关市": "Shaoguan",
    "河源市": "Heyuan",
    "梅州市": "Meizhou",
    "潮州市": "Chaozhou",
    "汕头市": "Shantou",
    "揭阳市": "Jieyang",
    "汕尾市": "Shanwei",
    "惠州市": "Huizhou",
    "东莞市": "Dongguan",
    "珠海市": "Zhuhai",
    "中山市": "zhongshan ",
    "江门市": "Jiangmen",
    "佛山市": "Foshan",
    "肇庆市": "Zhaoqing",
    "云浮市": "Yunfu",
    "阳江市": "Yangjiang",
    "茂名市": "Maoming",
    "湛江市": "Zhanjiang",
    "英德市": "Yingde ",
    "连州市": "Lianzhou",
    "乐昌市": "Lechang",
    "南雄市": "Nanxiong",
    "兴宁市": "Xingning",
    "普宁市": "Puning",
    "陆丰市": "Lufeng",
    "恩平市": "enping ",
    "台山市": "Taishan",
    "开平市": "Kaiping",
    "鹤山市": "Heshan",
    "四会市": "Sihui",
    "罗定市": "Luoding ",
    "阳春市": "Yangchun ",
    "化州市": "Huazhou",
    "信宜市": "Xinyi",
    "高州市": "Gaozhou",
    "吴川市": "Wuchuan",
    "廉江市": "Lianjiang",
    "雷州市": "Leizhou",
    "南宁市": "Nanning",
    "桂林市": "Guilin",
    "柳州市": "Liuzhou",
    "梧州市": "Wuzhou",
    "贵港市": "Guigang",
    "玉林市": "Yulin",
    "钦州市": "Qinzhou",
    "北海市": "Beihai",
    "防城港市": "Fangchenggang",
    "崇左市": "Chongzuo",
    "百色市": "Baise",
    "河池市": "Hechi",
    "来宾市": "Laibin",
    "贺州市": "Hezhou ",
    "岑溪市": "cenxi ",
    "桂平市": "Guiping ",
    "北流市": "Beiliu ",
    "东兴市": "Dongxing",
    "凭祥市": "Pingxiang",
    "合山市": "Heshan ",
    "靖西市": "Jingxi",
    "平果市": "Pingguo",
    "荔浦市": "Lipu",
    "海口市": "Haikou",
    "三亚市": "The of Sanya",
    "三沙市": "Sansha ",
    "儋州市": "Danzhou",
    "文昌市": "Wenchang",
    "琼海市": "Qionghai",
    "万宁市": "Wanning",
    "东方市": "Dongfang",
    "五指山市": "Five Fingers Group",
    "成都市": "Chengdu",
    "广元市": "Guangyuan",
    "绵阳市": "Mianyang",
    "德阳市": "deyang ",
    "南充市": "Nanchong",
    "广安市": "Guang'an",
    "遂宁市": "Suining",
    "内江市": "Neijiang",
    "乐山市": "Leshan",
    "自贡市": "Zigong",
    "泸州市": "Luzhou",
    "宜宾市": "Yibin",
    "攀枝花市": "Panzhihua",
    "巴中市": "Bazhong",
    "达州市": "Dazhou",
    "资阳市": "Ziyang",
    "眉山市": "Meishan",
    "雅安市": "Ya'an",
    "崇州市": "Chongzhou ",
    "邛崃市": "Qionglai",
    "都江堰市": "Dujiangyan Irrigation Project",
    "彭州市": "Pengzhou",
    "江油市": "Jiangyou",
    "什邡市": "Shifang",
    "广汉市": "Guanghan ",
    "绵竹市": "Mianzhu",
    "阆中市": "Langzhong ",
    "华蓥市": "Huaying ",
    "峨眉山市": "Emeishan ",
    "万源市": "Wanyuan",
    "简阳市": "Jianyang ",
    "西昌市": "Xichang",
    "康定市": "Kangding",
    "马尔康市": "Malcolm",
    "隆昌市": "Longchang",
    "射洪市": "Shehong",
    "会理市": "Huili",
    "贵阳市": "Guiyang",
    "六盘水市": "liupanshui ",
    "遵义市": "Zunyi",
    "安顺市": "Anshun",
    "毕节市": "Bijie",
    "铜仁市": "Tongren ",
    "清镇市": "qingzhen ",
    "赤水市": "Chishui ",
    "仁怀市": "Renhuai ",
    "凯里市": "Kaili ",
    "都匀市": "Duyun",
    "兴义市": "Xingyi ",
    "福泉市": "fuquan ",
    "盘州市": "Panzhou",
    "兴仁市": "Xingren",
    "昆明市": "Kunming",
    "曲靖市": "Qujing ",
    "玉溪市": "YuXi ",
    "丽江市": "lijiang ",
    "昭通市": "zhaotong ",
    "普洱市": "Pu'er",
    "临沧市": "Lincang",
    "保山市": "baoshan ",
    "安宁市": "Anning ",
    "宣威市": "Xuanwei",
    "芒市": "Mangshi",
    "瑞丽市": "Ruili",
    "大理市": "Dali",
    "楚雄市": "Chuxiong",
    "个旧市": "Gejiu",
    "开远市": "Kaiyuan ",
    "蒙自市": "Mengzi",
    "弥勒市": "Maitreya",
    "景洪市": "Jinghong",
    "文山市": "Wenshan",
    "香格里拉市": "Shangri La",
    "腾冲市": "Tengchong",
    "水富市": "Shuifu",
    "澄江市": "Chengjiang",
    "泸水市": "Lushui",
    "西安市": "Xi'an",
    "延安市": "Yan'an",
    "铜川市": "Tongchuan",
    "渭南市": "Weinan",
    "咸阳市": "Xianyang",
    "宝鸡市": "Baoji",
    "汉中市": "Hanzhong",
    "榆林市": "Yulin",
    "商洛市": "shangluo ",
    "安康市": "Ankang",
    "韩城市": "Hancheng ",
    "华阴市": "Huayin ",
    "兴平市": "xingping ",
    "彬州市": "Binzhou",
    "神木市": "Shenmu",
    "子长市": "Zichang",
    "兰州市": "Lanzhou",
    "嘉峪关市": "Jiayuguan",
    "金昌市": "Jinchang ",
    "白银市": "Baiyin",
    "天水市": "Tianshui",
    "酒泉市": "jiuquan ",
    "张掖市": "Zhangye",
    "武威市": "Wuwei",
    "庆阳市": "qingyang ",
    "平凉市": "Pingliang ",
    "定西市": "dingxi ",
    "陇南市": "Longnan",
    "玉门市": "Yumen",
    "敦煌市": "Dunhuang ",
    "临夏市": "Linxia",
    "合作市": "Cooperative",
    "华亭市": "Huating",
    "西宁市": "Xining",
    "海东市": "Haidong",
    "格尔木市": "Golmud",
    "德令哈市": "Delingha",
    "玉树市": "Yushu ",
    "茫崖市": "Mangya",
    "拉萨市": "Lhasa",
    "日喀则市": "Shigatse",
    "昌都市": "Changdu",
    "林芝市": "Linzhi",
    "山南市": "Shannan",
    "那曲市": "Nagqu",
    "银川市": "Yinchuan",
    "石嘴山市": "Shizuishan",
    "吴忠市": "Wuzhong",
    "中卫市": "Zhongwei",
    "固原市": "Guyuan",
    "灵武市": "Lingwu",
    "青铜峡市": "Qingtongxia",
    "乌鲁木齐市": "Urumqi",
    "克拉玛依市": "Karamay",
    "吐鲁番市": "Turpan",
    "哈密市": "Hami",
    "喀什市": "Kashgar",
    "阿克苏市": "Aksu",
    "库车市": "Kuqa",
    "和田市": "Hotan",
    "阿图什市": "Artux ",
    "阿拉山口市": "Alashankou",
    "博乐市": "Bole ",
    "昌吉市": "Changji",
    "阜康市": "Fukang ",
    "库尔勒市": "Korla",
    "伊宁市": "Yining",
    "奎屯市": "Kuitun",
    "塔城市": "Tacheng",
    "乌苏市": "Wusu ",
    "阿勒泰市": "Altay",
    "霍尔果斯市": "Khorgos",
    "石河子市": "Shihezi",
    "阿拉尔市": "Alar",
    "图木舒克市": "Tumshuk",
    "五家渠市": "Wujiaqu",
    "北屯市": "Beitun",
    "铁门关市": "Tiemenguan",
    "双河市": "Shuanghe",
    "可克达拉市": "Kekdara",
    "昆玉市": "Kunyu",
    "胡杨河市": "Huyanghe",
    "台北市": "Taipei",
    "新北市": "New Taipei",
    "桃园市": "Taoyuan",
    "台中市": "Taichung",
    "台南市": "Tainan",
    "高雄市": "Kaohsiung",
    "基隆市": "Keelung",
    "新竹市": "Hsinchu",
    "嘉义市": "Jiayi",
    // 香港特别行政区 三个主要地理区域
    "香港岛": "Hong Kong Island",
    "九龙": "Kowloon",
    "新界": "New Territories",
    // 香港特别行政区 三级区县
    "中西区": "Central and Western Regions",
    "湾仔区": "Wan Chai District",
    "东区": "East Area",
    "南区": "South Area",
    "油尖旺区": "Yau Tsim Mong District",
    "深水埗区": "Sham Shui Po District",
    "九龙城区": "Kowloon",
    "黄大仙区": "Wong Tai Sin District",
    "观塘区": "Kwun Tong District",
    "荃湾区": "Tsuen Wan District",
    "屯门区": "Tuen Mun District",
    "元朗区": "Yuen Long District",
    "北区": "North Area",
    "大埔区": "Dapu District",
    "西贡区": "Saigon District",
    "沙田区": "Sha Tin District",
    "葵青区": "Kuiqing District",
    "离岛区": "Islands District",
    // 澳门特别行政区
    "嘉模堂区": "Kamodang District",
    "花王堂区": "Kao Parish",
    "望德堂区": "São Lázaro",
    "圣方济各堂区": "St. Francis Parish",
    "花地玛堂区": "Flower Field Parish",
    "路氹填海区": "Cotai Reclamation District",
    "风顺堂区": "Wind Shun Parish",
    "大堂区": "Lobby District",
    "阿里地区": "Ngari Prefecture",
    // 天津
    "和平区": "Heping District",
    "河东区": "Hedong District",
    "河西区": "Hexi District",
    "南开区": "Nankai District",
    "河北区": "Hebei District",
    "红桥区": "Hongqiao District",
    "塘沽区": "Tanggu District",
    "汉沽区": "Hangu District",
    "大港区": "Dagang District",
    "西青区": "Xiqing District",
    "东丽区": "Dongli District",
    "津南区": "Jinnan District",
    "北辰区": "Beichen District",
    "武清区": "Wuqing District",
    "宝坻区": "Baodi District",
    "滨海新区": "Binhai New Area",
    "静海区": "Jinghai District",
    "宁河区": "Ninghe District",
    "蓟州区": "Jizhou District",
    // 上海
    "宝山区": "Baoshan District",
    "嘉定区": "Jiading District",
    "川沙区": "Chuansha District",
    "上海县": "Shanghai County",
    "南汇区": "Nanhui District",
    "奉贤区": "Fengxian District",
    "松江区": "Songjiang District",
    "金山区": "Jinshan District",
    "青浦区": "Qingpu District",
    "崇明区": "Chongming District",
    "黄浦区": "Huangpu District",
    "静安区": "Jing'an District",
    "南市区": "Nanshi District",
    "普陀区": "Putuo District",
    "长宁区": "Changning District",
    "卢湾区": "Luwan District",
    "徐汇区": "Xuhui District",
    "闸北区": "Zhabei District",
    "虹口区": "Hongkou District",
    "杨浦区": "Yangpu District",
    "闵行区": "Minhang District",
    "浦东新区": "Pudong New Area",
    // 北京
    "东城区": "Dongcheng District",
    "西城区": "Xicheng District",
    "朝阳区": "Chaoyang District",
    "丰台区": "Fengtai District",
    "石景山区": "Shijingshan District",
    "海淀区": "Haidian District",
    "门头沟区": "Mentougou District",
    "房山区": "Fangshan District",
    "大兴区": "Daxing District",
    "通州区": "Tongzhou District",
    "顺义区": "Shunyi District",
    "昌平区": "Changping District",
    "怀柔区": "Huairou District",
    "平谷区": "Pinggu District",
    "密云区": "Miyun District",
    "延庆区": "Yanqing District",
    // 重庆
    "重庆郊县": "Chongqing Suburban",
    "重庆城区": "Chongqing Urban",

};

export default provinceCityMapping;